export const iosProducts = [
  {
    id: 1,
    name: 'iPhone 15 Pro Max',
    category: 'Smartphone',
    os: 'iOS 17',
    price: 1199,
    releaseYear: 2023,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro',
    category: 'Smartphone',
    os: 'iOS 17',
    price: 1099,
    releaseYear: 2023,
  },
  {
    id: 3,
    name: 'iPhone 15 Plus',
    category: 'Smartphone',
    os: 'iOS 17',
    price: 899,
    releaseYear: 2023,
  },
  {
    id: 4,
    name: 'iPhone 15',
    category: 'Smartphone',
    os: 'iOS 17',
    price: 799,
    releaseYear: 2023,
  },
  {
    id: 5,
    name: 'iPhone 14 Pro Max',
    category: 'Smartphone',
    os: 'iOS 16',
    price: 1099,
    releaseYear: 2022,
  },
  {
    id: 6,
    name: 'iPhone 14 Pro',
    category: 'Smartphone',
    os: 'iOS 16',
    price: 999,
    releaseYear: 2022,
  },
  {
    id: 7,
    name: 'iPhone 14 Plus',
    category: 'Smartphone',
    os: 'iOS 16',
    price: 899,
    releaseYear: 2022,
  },
  {
    id: 8,
    name: 'iPhone 14',
    category: 'Smartphone',
    os: 'iOS 16',
    price: 799,
    releaseYear: 2022,
  },
  {
    id: 9,
    name: 'iPhone 13',
    category: 'Smartphone',
    os: 'iOS 15',
    price: 699,
    releaseYear: 2021,
  },
  {
    id: 10,
    name: 'iPhone SE (3rd generation)',
    category: 'Smartphone',
    os: 'iOS 17',
    price: 429,
    releaseYear: 2022,
  },
  {
    id: 11,
    name: 'iPad Pro 12.9-inch (6th generation)',
    category: 'Tablet',
    os: 'iPadOS 17',
    price: 1099,
    releaseYear: 2022,
  },
  {
    id: 12,
    name: 'iPad Pro 11-inch (4th generation)',
    category: 'Tablet',
    os: 'iPadOS 17',
    price: 799,
    releaseYear: 2022,
  },
  {
    id: 13,
    name: 'iPad Air (5th generation)',
    category: 'Tablet',
    os: 'iPadOS 17',
    price: 599,
    releaseYear: 2022,
  },
  {
    id: 14,
    name: 'iPad (10th generation)',
    category: 'Tablet',
    os: 'iPadOS 17',
    price: 449,
    releaseYear: 2022,
  },
  {
    id: 15,
    name: 'iPad mini (6th generation)',
    category: 'Tablet',
    os: 'iPadOS 17',
    price: 499,
    releaseYear: 2021,
  },
  {
    id: 16,
    name: 'iPod touch (7th generation)',
    category: 'Media Player',
    os: 'iOS 15',
    price: 199,
    releaseYear: 2019,
    discontinued: true,
  },
  {
    id: 17,
    name: 'iPhone 12',
    category: 'Smartphone',
    os: 'iOS 14',
    price: 599,
    releaseYear: 2020,
  },
  {
    id: 18,
    name: 'iPhone 11',
    category: 'Smartphone',
    os: 'iOS 13',
    price: 499,
    releaseYear: 2019,
  },
  {
    id: 19,
    name: 'iPhone XR',
    category: 'Smartphone',
    os: 'iOS 12',
    price: 499,
    releaseYear: 2018,
    discontinued: true,
  },
  {
    id: 20,
    name: 'iPad (9th generation)',
    category: 'Tablet',
    os: 'iPadOS 15',
    price: 329,
    releaseYear: 2021,
  },
];
